### PR TITLE
Fix games not playing in survival

### LINKED ISSUE #23: Fire charges / flint & steel / lava don't work in-game
possible culprit: https://github.com/DumbDogDiner/StickySurvival/blob/2491e44a1cb6f959129bfea44ec4f536c2687b73/src/main/kotlin/com/dumbdogdiner/stickysurvival/listener/GameEventsListener.kt#L282-L285

### PR DESCRIPTION
**Pull request by jcxldn**
Kind of a workaround to preserve game functionality (eg. not adding another phase) whilst keeping the gamemode listener mostly functional

### CODE REVIEW

**Comment by jcxldn** [comment]
Fixes #23.

File: src/main/kotlin/com/dumbdogdiner/stickysurvival/game/GameStartComponent.kt [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package com.dumbdogdiner.stickysurvival.game
+
+import com.dumbdogdiner.stickysurvival.Game
+import com.dumbdogdiner.stickysurvival.event.GameStartEvent
+import org.bukkit.event.EventHandler
+import org.bukkit.event.EventPriority
+
+class GameStartComponent(game: Game) : GameComponent(game) {
+    @EventHandler(priority = EventPriority.MONITOR)
```
Comment (jcxldn) [inline src/main/kotlin/com/dumbdogdiner/stickysurvival/game/GameStartComponent.kt:11]: Just gonna add a comment here explaining priority...
